// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdextwtn97oUWiYovvL8GoY1SIOkWrcRI',
    appId: '1:206938205714:web:484a93203fd14e39d2b2cb',
    messagingSenderId: '206938205714',
    projectId: 'campph-b6b02',
    authDomain: 'campph-b6b02.firebaseapp.com',
    storageBucket: 'campph-b6b02.firebasestorage.app',
    measurementId: 'G-SQ55MSSR38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHreY2OcsWEj7wb_774-t45WcODoMbws',
    appId: '1:206938205714:android:19eff1d2d4027e72d2b2cb',
    messagingSenderId: '206938205714',
    projectId: 'campph-b6b02',
    storageBucket: 'campph-b6b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTCu9bpT99KBNjG6O7QQsFM7FslV1FgU4',
    appId: '1:206938205714:ios:dfd14a379ad50d27d2b2cb',
    messagingSenderId: '206938205714',
    projectId: 'campph-b6b02',
    storageBucket: 'campph-b6b02.firebasestorage.app',
    iosBundleId: 'com.example.camph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTCu9bpT99KBNjG6O7QQsFM7FslV1FgU4',
    appId: '1:206938205714:ios:dfd14a379ad50d27d2b2cb',
    messagingSenderId: '206938205714',
    projectId: 'campph-b6b02',
    storageBucket: 'campph-b6b02.firebasestorage.app',
    iosBundleId: 'com.example.camph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdextwtn97oUWiYovvL8GoY1SIOkWrcRI',
    appId: '1:206938205714:web:a64ab17e2e08a044d2b2cb',
    messagingSenderId: '206938205714',
    projectId: 'campph-b6b02',
    authDomain: 'campph-b6b02.firebaseapp.com',
    storageBucket: 'campph-b6b02.firebasestorage.app',
    measurementId: 'G-D3L49XTF84',
  );
}
